<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <InternalsVisibleTo Include="SafetySystems.SafetyAudit.Test" />
    </ItemGroup>

    <ItemGroup>
    <PackageReference Include="Ardalis.Result.FluentValidation" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="SonarAnalyzer.CSharp">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Remediation\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SafetySystems.SafetyAudit.Infrastructure\SafetySystems.SafetyAudit.Infrastructure.csproj" />
  </ItemGroup>

</Project>
