// <auto-generated />
using System;
using LoneWorkerCheckin.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoneWorkerCheckin.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240828192223_AddedLocations")]
    partial class AddedLocations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.LocationEntity", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationName")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            LocationId = new Guid("774e9499-fb15-4995-8dc8-43610a5f5b53"),
                            LocationName = "Kitchen"
                        },
                        new
                        {
                            LocationId = new Guid("6d55a9ed-e128-4366-97d0-eddcb6fa7c58"),
                            LocationName = "Dinning room"
                        },
                        new
                        {
                            LocationId = new Guid("2ac4032b-240f-4029-9d64-d20848c8d694"),
                            LocationName = "Reception"
                        });
                });

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.RegionEntity", b =>
                {
                    b.Property<Guid>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RegionId");

                    b.HasIndex("RegionName")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            RegionId = new Guid("7736d6df-d93d-42c8-82c3-639bfd7b326f"),
                            RegionName = "South East"
                        },
                        new
                        {
                            RegionId = new Guid("7d45913f-2062-41e6-8da5-2d9f3b259552"),
                            RegionName = "South West"
                        },
                        new
                        {
                            RegionId = new Guid("cd5aa765-ace1-4cf0-bd8d-141eca83a8e1"),
                            RegionName = "Southern"
                        },
                        new
                        {
                            RegionId = new Guid("0e817f5c-e063-4d2a-aca5-0e40b52dd0ce"),
                            RegionName = "Northern"
                        },
                        new
                        {
                            RegionId = new Guid("6cc76f4a-5c6d-4f25-b898-0ffeaec0af1f"),
                            RegionName = "Scotland"
                        },
                        new
                        {
                            RegionId = new Guid("04d82d36-3c9a-4b57-94f0-509574eb1523"),
                            RegionName = "Wales"
                        },
                        new
                        {
                            RegionId = new Guid("c5b96f86-2305-4a90-b3cf-cd8300c28017"),
                            RegionName = "Middle England"
                        });
                });

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.SiteEntity", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SiteId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SiteName")
                        .IsUnique();

                    b.ToTable("Sites", (string)null);

                    b.HasData(
                        new
                        {
                            SiteId = new Guid("bfde935e-abe4-4d64-9c36-2cfb172fae99"),
                            RegionId = new Guid("7736d6df-d93d-42c8-82c3-639bfd7b326f"),
                            SiteName = "Horsham"
                        },
                        new
                        {
                            SiteId = new Guid("c9ab9a01-b18f-4fbb-8acd-27359fd52c0d"),
                            RegionId = new Guid("7736d6df-d93d-42c8-82c3-639bfd7b326f"),
                            SiteName = "Brighton"
                        },
                        new
                        {
                            SiteId = new Guid("e961b53c-e82b-453e-b814-ecddc031e953"),
                            RegionId = new Guid("04d82d36-3c9a-4b57-94f0-509574eb1523"),
                            SiteName = "Cardiff"
                        },
                        new
                        {
                            SiteId = new Guid("cc53d272-23e7-436d-b5a5-c3a235cdb2fd"),
                            RegionId = new Guid("04d82d36-3c9a-4b57-94f0-509574eb1523"),
                            SiteName = "Bangor"
                        });
                });

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.SiteEntity", b =>
                {
                    b.HasOne("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.RegionEntity", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
