<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <UserSecretsId>dotnet-SafetySystems.Common.EFDataMigrationService-31425e8f-cae2-46d9-a9ad-c919076ccccb</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\LoneWorkerCheckin\SafetySystems.LoneWorkerCheckin.Infrastructure\SafetySystems.LoneWorkerCheckin.Infrastructure.csproj" />
      <ProjectReference Include="..\SafetySystems.Common.ServiceDefaults\SafetySystems.Common.ServiceDefaults.csproj" />
    </ItemGroup>
</Project>
