using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.Remediation.ResolutionsRequest.SiteInspectionReportId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.Remediation.ResolutionsRequest.ResolutionId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.Remediation.ResolutionsRequest.DateOfResolutions")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.Remediation.ResolutionsRequest.RiskFindingId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.Remediation.ResolutionsRequest.ResolutionStatusId")]

[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.SiteInspectionReportRequest.SiteId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.SiteInspectionReportRequest.AuditorId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.SiteInspectionReportRequest.DateOfInspection")]

[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.RiskFindingRequest.SiteId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.RiskFindingRequest.AuditorId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.RiskFindingRequest.SpecificIssueRiskId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.RiskFindingRequest.RiskCodeId")]
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Value type input is validated via FluentValidation (NotEmpty); under-posting is explicitly handled and returns ValidationProblemDetails.", Scope = "member", Target = "~P:SafetySystems.SafetyAudit.Api.SafetyInspection.RiskFindingRequest.DateOfInspection")]

