<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
      <PackageReference Include="SonarAnalyzer.CSharp">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\SafetySystems.Common.ServiceDefaults\SafetySystems.Common.ServiceDefaults.csproj" />
    <ProjectReference Include="..\SafetySystems.SafetyAudit.Application\SafetySystems.SafetyAudit.Application.csproj" />
    <ProjectReference Include="..\SafetySystems.SafetyAudit.Domain\SafetySystems.SafetyAudit.Domain.csproj" />
    <ProjectReference Include="..\SafetySystems.SafetyAudit.Infrastructure\SafetySystems.SafetyAudit.Infrastructure.csproj" />
  </ItemGroup>

</Project>
