// <auto-generated />
using System;
using SafetySystems.LoneWorkerCheckin.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SafetySystems.LoneWorkerCheckin.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241107185118_AddedCheckins")]
    partial class AddedCheckins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.CheckinEntity", b =>
                {
                    b.Property<Guid>("CheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CheckinId");

                    b.ToTable("Checkins", (string)null);
                });

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.LocationEntity", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationName")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            LocationId = new Guid("1a86e167-a21c-4467-9beb-1e63b08d371f"),
                            LocationName = "Kitchen"
                        },
                        new
                        {
                            LocationId = new Guid("8aec57a1-4918-4772-aea5-1e0fddd68c6d"),
                            LocationName = "Dinning room"
                        },
                        new
                        {
                            LocationId = new Guid("27efc204-445e-4321-a845-8a72d7f84f71"),
                            LocationName = "Reception"
                        });
                });

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.RegionEntity", b =>
                {
                    b.Property<Guid>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RegionId");

                    b.HasIndex("RegionName")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);

                    b.HasData(
                        new
                        {
                            RegionId = new Guid("6b7331db-983b-4724-8a24-12951aab38b6"),
                            RegionName = "South East"
                        },
                        new
                        {
                            RegionId = new Guid("506ccb78-dac0-4e18-96a1-d014b61c58da"),
                            RegionName = "South West"
                        },
                        new
                        {
                            RegionId = new Guid("1cc438b5-ffae-4fc2-8045-be779200b829"),
                            RegionName = "Southern"
                        },
                        new
                        {
                            RegionId = new Guid("ac2fa921-b9e5-4c44-9795-f60ed999e0c4"),
                            RegionName = "Northern"
                        },
                        new
                        {
                            RegionId = new Guid("fe07a80f-b774-4b15-b496-a8db27a4d5ef"),
                            RegionName = "Scotland"
                        },
                        new
                        {
                            RegionId = new Guid("030f5eaf-d8c1-4489-b871-737ee8e06ed1"),
                            RegionName = "Wales"
                        },
                        new
                        {
                            RegionId = new Guid("5ba01a1e-51f4-49b0-b4f7-512ed3746433"),
                            RegionName = "Middle England"
                        });
                });

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.SiteEntity", b =>
                {
                    b.Property<Guid>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SiteId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SiteName")
                        .IsUnique();

                    b.ToTable("Sites", (string)null);

                    b.HasData(
                        new
                        {
                            SiteId = new Guid("e915faba-37a8-4dc9-8d03-1b9196edc227"),
                            RegionId = new Guid("6b7331db-983b-4724-8a24-12951aab38b6"),
                            SiteName = "Horsham"
                        },
                        new
                        {
                            SiteId = new Guid("ef227e96-c100-42bc-af5b-b08e1d215d64"),
                            RegionId = new Guid("6b7331db-983b-4724-8a24-12951aab38b6"),
                            SiteName = "Brighton"
                        },
                        new
                        {
                            SiteId = new Guid("4583d6d5-56ea-4701-8188-2cb29af75ab1"),
                            RegionId = new Guid("030f5eaf-d8c1-4489-b871-737ee8e06ed1"),
                            SiteName = "Cardiff"
                        },
                        new
                        {
                            SiteId = new Guid("81b1a919-6e37-4c4f-af7c-76cc4be85811"),
                            RegionId = new Guid("030f5eaf-d8c1-4489-b871-737ee8e06ed1"),
                            SiteName = "Bangor"
                        });
                });

            modelBuilder.Entity("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.SiteEntity", b =>
                {
                    b.HasOne("LoneWorkerCheckin.Infrastructure.EntityFramework.Models.RegionEntity", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
