<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0-rc.1.24511.1" />

    <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>f226c6a5-6325-4d06-a480-f887280a9c3c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LoneWorkerCheckin\SafetySystems.LoneWorkerCheckin.Api\SafetySystems.LoneWorkerCheckin.Api.csproj" />
    <ProjectReference Include="..\..\LoneWorkerCheckin\SafetySystems.LoneWorkerCheckin.Blazor\SafetySystems.LoneWorkerCheckin.Blazor.csproj" />
    <ProjectReference Include="..\..\LoneWorkerCheckin\SafetySystems.LoneWorkerCheckin.Infrastructure\SafetySystems.LoneWorkerCheckin.Infrastructure.csproj">
        <IsAspireProjectResource>false</IsAspireProjectResource>
    </ProjectReference>
    <ProjectReference Include="..\..\SafetyAudit\SafetySystems.SafetyAudit.Api\SafetySystems.SafetyAudit.Api.csproj" />
    <ProjectReference Include="..\..\SafetyAudit\SafetySystems.SafetyAudit.Blazor\SafetySystems.SafetyAudit.Blazor.csproj" />
    <ProjectReference Include="..\SafetySystems.Common.EFDataMigrationService\SafetySystems.Common.EFDataMigrationService.csproj" />
  </ItemGroup>

</Project>
