<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\SafetySystems.SafetyAudit.Domain\SafetySystems.SafetyAudit.Domain.csproj" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>

</Project>
