<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
      <PackageReference Include="SonarAnalyzer.CSharp">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EntityFramework\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SafetySystems.LoneWorkerCheckin.Domain\SafetySystems.LoneWorkerCheckin.Domain.csproj" />
  </ItemGroup>

</Project>
